# Generated by Django 5.1 on 2024-11-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        ('main', '0002_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructordiscussion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentdiscussion',
            options={},
        ),
        migrations.RemoveField(
            model_name='instructordiscussion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentdiscussion',
            name='status',
        ),
        migrations.AddField(
            model_name='instructordiscussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion.instructordiscussion'),
        ),
        migrations.AddField(
            model_name='studentdiscussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion.studentdiscussion'),
        ),
        migrations.AlterField(
            model_name='instructordiscussion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instructordiscussion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='instructordiscussion',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instructor'),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
