# Generated by Django 5.1.3 on 2024-11-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_instructordiscussion_options_and_more'),
        ('main', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructordiscussion',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='studentdiscussion',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveField(
            model_name='instructordiscussion',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentdiscussion',
            name='parent',
        ),
        migrations.AlterField(
            model_name='instructordiscussion',
            name='content',
            field=models.TextField(max_length=1600),
        ),
        migrations.AlterField(
            model_name='instructordiscussion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseDiscussions', to='main.course'),
        ),
        migrations.AlterField(
            model_name='instructordiscussion',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseDiscussions', to='main.instructor'),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='content',
            field=models.TextField(max_length=1600),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='main.course'),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='main.student'),
        ),
    ]
