# Generated by Django 5.1.3 on 2024-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/default_student.webp', upload_to='profile_pics'),
        ),
    ]
